### ISSUE TITLE
Add support for decoding JWT tokens

### ISSUE THREAD

**Issue by moritz89** [urbanplatform/django-keycloak-auth#1]
Since the JWT tokens are signed, it is possible to create a parallel code path to introspecting tokens with the server. This would reduce the load on the Keycloak server and reduce the latency for requests.

I have implemented and tested this and if there is interest, I would gladly upstream the changes.

The introspection code path is preserved and can be toggled with a setting flag.

**Comment by ftcardoso** [comment]
Hi @moritz89! 

Sure, you can upstream the changes, we gladly accept all the help. For now, keep them in a separate branch and then we can merge into the main.

**Comment by moritz89** [comment]
You mentioned branch. Should I create a pull request or what is your preferred method?

**Comment by ftcardoso** [comment]
Yes, pull request. Thanks!
