### ISSUE TITLE
Use python-keycloak as the library to interface with Keycloak

### ISSUE THREAD

**Issue by moritz89** [urbanplatform/django-keycloak-auth#12]
Just wanted to ask if you'd be interested in using [python-keycloak](https://github.com/marcospereirampj/python-keycloak) as the interface to Keycloak? It is a well tested library to interface with Keycloak API

**Comment by uw-rvitorino** [comment]
Hi @moritz89 do you see concrete use cases for this? Where do you think it would be useful to test the Python lib in the current code base?
