### ISSUE TITLE
Formatting rules

### ISSUE THREAD

**Issue by moritz89** [urbanplatform/django-keycloak-auth#2]
If contributions are welcome, it would be of use to have a set of formatting rules to keep a consistent and automatically formatted code base. Is such a set of rules available?

**Comment by ftcardoso** [comment]
Hi @moritz89! 

Yes, contributions are welcome! Currently there is no set of rules... Any suggestion regarding that?

**Comment by moritz89** [comment]
[Black](https://github.com/psf/black) is a comprehensive formatter that I've had good experiences with. The most important aspect for me is that there is a standard and I don't have to think about the formatting :smile:

**Comment by ftcardoso** [comment]
Did a quick test with [Black](https://github.com/psf/black) and I think we can go with it! I will run it through the repo and format all the files. We will also check some GitHub action to validate or event format on push/PR. Thanks!

**Comment by ftcardoso** [comment]
Added action for code validation based on your recommendation.
