### ISSUE TITLE
Is this installable with pip?

### ISSUE THREAD

**Issue by Wissperwind** [urbanplatform/django-keycloak-auth#24]
Hi,

There is a release, cool. But is this installable with pip? Maybe by using an url and not the name?

**Comment by Wissperwind** [comment]
Well, I think it is. But the name is not the one from the project title because it is already in use.
It would be extraordniary if you would write on the frontpage that the name for installation is django-uw-keycloak.

**Comment by moritz89** [comment]
I just tried to get in touch with the previous maintainers at urban platform but the email bounced for both. It is an integral part of my project and might create my own package from it.

**Comment by Wissperwind** [comment]
Let me know if you do so.

**Comment by rjfv** [comment]
Hi @moritz89 I will get in touch with you via email regarding this project! Thank you so much for all your contributions and interest, and please apologise for the email issues beforehand. /cc @Wissperwind

**Comment by simao-silva** [comment]
@Wissperwind I added in [fd8e975](https://github.com/urbanplatform/django-keycloak-auth/commit/fd8e975c50a5281afed9dcdd7e3e4fe0c06bb866) the installation with pip as well as compiling from source. I believe this issue is now resolved.
