### ISSUE TITLE
Could we make URLs more configurable?

### ISSUE THREAD

**Issue by Wissperwind** [urbanplatform/django-keycloak-auth#27]
I would love to use this library without changing the code.
The URLs are configured in urls.py. In my case I have to remove the /auth from every url because our IT has removed that from the keycloak urls.
Can we add an option to this library to make URLs configurable in settings.py?

**Comment by Wissperwind** [comment]
Thanks alot. Looking forward to their response.

**Comment by moritz89** [comment]
We've gotten the ball rolling again and will be pushing the merge requests one after another and then also creating a new release for this library

**Comment by uw-rvitorino** [comment]
Closing this issue since we've just merged #29 🎉 🥳 🥂
