### ISSUE TITLE
IntegrityError: null value in column "email" violates not-null constraint

### ISSUE THREAD

**Issue by uw-rvitorino** [urbanplatform/django-keycloak-auth#38]
**Describe the bug**
**IntegrityError** `django_keycloak.middleware in append_user_info_to_request error`
_null value in column "email" violates not-null constraint_

`django_keycloak/middleware.py` in `append_user_info_to_request` (line 39) raises this error when the `user_info` does not contain the `email` property (because the Token is not valid anymore)

**To Reproduce**
1. Login with your credentials in a UI calling a Django API served by this library
2. Remain in the UI and allow your token to expire 
3. Click somewhere that calls the Django API
4. See error crashing the Django project

**Expected behavior**
The middleware should try to get the email from the user info but if it's None it should return an Unauthorised response and not try to save the user info,

**Screenshots**
![Screenshot 2022-10-20 at 18 22 12](https://user-images.githubusercontent.com/115562920/197016975-4ee44404-dce6-4e9c-9168-5838dc79a6b8.png)

**Desktop (please complete the following information):**
 - OS: Not relevant
 - Browser: Not relevant
 - Version: Not relevant

**Smartphone (please complete the following information):**
 - Device: Not relevant
 - OS: Not relevant
 - Browser: Not relevant
 - Version: Not relevant

**Additional context**
N/A

**Comment by moritz89** [comment]
Ah yes, we would probably use a `raise_on_error` function to check the responses of all Keycloak calls. Basically everywhere `requests.request()` is called

**Comment by moritz89** [comment]
Could you test if this issue still persists in the v2 branch. AFAIK, this has been solved
