### ISSUE TITLE
Fix package publishing

### ISSUE THREAD

**Issue by moritz89** [urbanplatform/django-keycloak-auth#43]
@uw-rvitorino To publish v2 of the package the following has to be fixed

**Describe the bug**
Moved to Poetry as the dependency / packaging tool but the GitHub action still uses the legacy method.

Guide to update the `python-publish.yml` action file: https://python-poetry.org/docs/libraries/#packaging

It should just be:
1. `poetry build`
2. `poetry publish`

`poetry publish` has been tested to work locally.

**Comment by uw-rvitorino** [comment]
Do you mean doing it manually in the command-line?

**Comment by moritz89** [comment]
Seems to work just fine. Was worried that the new format in pyproject.toml wouldn't work with the existing publishing pipeline
