### ISSUE TITLE
[bug] user with no email in keycloak are failing to login in Django

### ISSUE THREAD

**Issue by yalattas** [urbanplatform/django-keycloak-auth#46]
**Describe the bug**
A user has been registered to keyCloak and has username and password but no email (username can be phone number OR a string).
if user attempts to login into Django backend, Django is throwing `IntegrityError`

**To Reproduce**
1. create a user in KeyCloak but don't assign an email. _make it optional_
2. generate a credentials for that user
3. visit Django admin page EX: `http://localhost:8000/admin/`
4. put username and password same as KeyCloak
5. You will see the error

workaround:
1. after seeing the error, Go back to keyCloak and assign any email to that user.
2. Now you can login to Django admin

**Expected behavior**
Allowing access to Django admin with no email

**Screenshots**
![image](https://user-images.githubusercontent.com/38978501/199483352-ee6da797-7a79-467e-946d-378ed8021b16.png)

**Desktop (please complete the following information):**
- docker container - backend - `FROM python:3.11-slim-bullseye`
- docker container - IAM - `FROM quay.io/keycloak/keycloak:18.0`

**Additional context**
Main dependencies
```
djangorestframework==3.14.0
Django==4.1.3
django-uw-keycloak==2.0.1
python-keycloak==2.6.0
```

**Comment by moritz89** [comment]
Probably use `AUTH_USER_MODEL = "django_keycloak.KeycloakUser"` in your settings. However, this will limit functionality of saving user info into the DB. As your use-case is not a requirement of the core developers, I do not think they will take it up, but if you submit a quality MR, they're open to improvements.
