### ISSUE TITLE
Add stale bot to handle inactive issues and PRs

### ISSUE THREAD

**Issue by moritz89** [urbanplatform/django-keycloak-auth#47]
**Is your feature request related to a problem? Please describe.**
Not a problem yet, but handle issues that are not active anymore

**Describe the solution you'd like**
Add a bot to mark old issues as stale with (e.g., https://github.com/marketplace/actions/close-stale-issues)

**Describe alternatives you've considered**
Manually tracking old and inactive issues

**Additional context**
This is standard with most larger projects. The default configuration of marking issues stale after 60 days, and closing them 7 days after that seems fine.

**Comment by simao-silva** [comment]
Hi,
I followed your time suggestions to stale and close issues and also added for PRs to keep us more proactive and aware of them.
