### ISSUE TITLE
Write in the documentation about configuring keycloak

### ISSUE THREAD

**Issue by talesmm14** [urbanplatform/django-keycloak-auth#99]
I was unable to authenticate after configuring the project, an error about incorrect password or username was always returned. After some debugging investigations into the library, I found the following exception in from_credentials in Token.

b'{"error":"unauthorized_client","error_description":"Client not permitted for direct access grants"}'

To resolve this issue, I had to configure my keycloak client to enable direct access.

![keycloak_config](https://github.com/urbanplatform/django-keycloak-auth/assets/29584893/647f5591-b2b1-47c7-8522-219040909410)

It would be interesting to see in the official documentation how the keycloak client must be configured for the library to work correctly.

**Comment by moritz89** [comment]
Thanks for the effort of opening a ticket, but this is won't be resolved given the project's limited resources. The initial owners have moved on, and while I still use and continue to improve it, I haven't published the changes. The direction has changed slightly to focus on async middleware but requires clean up before it can be published.
